import re

with open("app/admin/(protected)/dashboard/DashboardClient.tsx", "r") as f:
    content = f.read()

# First add the `isPromoter` flag where userRole is extracted
if "const isPromoter = " not in content:
    content = content.replace("const userRole = user.user_metadata?.role || 'Admin';", "const userRole = user.user_metadata?.role || 'Admin';\n    const isPromoter = userRole?.toUpperCase() === 'PROMOTOR';")

# 1. /admin/revendedoras
content = content.replace('<Link href="/admin/revendedoras">', '{!isPromoter ? (<Link href="/admin/revendedoras">')
content = content.replace('Gerenciar Consultoras</div>\n                                                <div className="text-xs text-slate-500" style={{ fontFamily: "var(--font-inter)" }}>{totalLeads} cadastradas</div>\n                                            </div>\n                                        </Button>\n                                    </Link>', 'Gerenciar Consultoras</div>\n                                                <div className="text-xs text-slate-500" style={{ fontFamily: "var(--font-inter)" }}>{totalLeads} cadastradas</div>\n                                            </div>\n                                        </Button>\n                                    </Link>) : (\n                                      <Button variant="ghost" disabled className="w-full justify-start text-slate-400 py-5 border border-white/30 rounded-2xl cursor-not-allowed">\n                                          <Users className="w-4 h-4 mr-3 text-slate-300" />\n                                          <div className="text-left">\n                                              <div className="font-medium" style={{ fontFamily: "var(--font-inter)" }}>Gerenciar Consultoras</div>\n                                              <div className="text-xs text-slate-400" style={{ fontFamily: "var(--font-inter)" }}>Bloqueado</div>\n                                          </div>\n                                      </Button>\n                                    )}')

# 2. /admin/estoque
content = content.replace('<Link href="/admin/estoque">', '{!isPromoter ? (<Link href="/admin/estoque">')
content = content.replace('Estoque Geral</div>\n                                                <div className="text-xs text-slate-500" style={{ fontFamily: "var(--font-inter)" }}>Gestão do CD</div>\n                                            </div>\n                                        </Button>\n                                    </Link>', 'Estoque Geral</div>\n                                                <div className="text-xs text-slate-500" style={{ fontFamily: "var(--font-inter)" }}>Gestão do CD</div>\n                                            </div>\n                                        </Button>\n                                    </Link>) : (\n                                      <Button variant="ghost" disabled className="w-full justify-start text-slate-400 py-5 border border-white/30 rounded-2xl cursor-not-allowed">\n                                          <Package className="w-4 h-4 mr-3 text-slate-300" />\n                                          <div className="text-left">\n                                              <div className="font-medium" style={{ fontFamily: "var(--font-inter)" }}>Estoque Geral</div>\n                                              <div className="text-xs text-slate-400" style={{ fontFamily: "var(--font-inter)" }}>Bloqueado</div>\n                                          </div>\n                                      </Button>\n                                    )}')

# 3. /admin/vendas
content = content.replace('<Link href="/admin/vendas">', '{!isPromoter ? (<Link href="/admin/vendas">')
content = content.replace('PDV / Vendas</div>\n                                                <div className="text-xs text-slate-500" style={{ fontFamily: "var(--font-inter)" }}>Registrar saídas</div>\n                                            </div>\n                                        </Button>\n                                    </Link>', 'PDV / Vendas</div>\n                                                <div className="text-xs text-slate-500" style={{ fontFamily: "var(--font-inter)" }}>Registrar saídas</div>\n                                            </div>\n                                        </Button>\n                                    </Link>) : (\n                                      <Button variant="ghost" disabled className="w-full justify-start text-slate-400 py-5 border border-white/30 rounded-2xl cursor-not-allowed">\n                                          <ShoppingCart className="w-4 h-4 mr-3 text-slate-300" />\n                                          <div className="text-left">\n                                              <div className="font-medium" style={{ fontFamily: "var(--font-inter)" }}>PDV / Vendas</div>\n                                              <div className="text-xs text-slate-400" style={{ fontFamily: "var(--font-inter)" }}>Bloqueado</div>\n                                          </div>\n                                      </Button>\n                                    )}')

# 4. Relatórios Detalhados Dialog
content = content.replace('<Dialog open={showDetailedReportModal} onOpenChange={setShowDetailedReportModal}>', '{!isPromoter ? (<Dialog open={showDetailedReportModal} onOpenChange={setShowDetailedReportModal}>')
content = content.replace('Visualizar Relatório\n                                                </Button>\n                                            </div>\n                                        </DialogContent>\n                                    </Dialog>', 'Visualizar Relatório\n                                                </Button>\n                                            </div>\n                                        </DialogContent>\n                                    </Dialog>) : (\n                                      <Button variant="ghost" disabled className="w-full justify-start text-slate-400 py-5 border border-white/30 rounded-2xl cursor-not-allowed">\n                                          <FileText className="w-4 h-4 mr-3 text-slate-300" />\n                                          <div className="text-left">\n                                              <div className="font-medium" style={{ fontFamily: "var(--font-inter)" }}>Relatórios Detalhados</div>\n                                              <div className="text-xs text-slate-400" style={{ fontFamily: "var(--font-inter)" }}>Bloqueado</div>\n                                          </div>\n                                      </Button>\n                                    )}')

# 5. Relatório por Promotor Dialog
content = content.replace('<Dialog open={showPromoterReportModal} onOpenChange={setShowPromoterReportModal}>', '{!isPromoter ? (<Dialog open={showPromoterReportModal} onOpenChange={setShowPromoterReportModal}>')
content = content.replace('Visualizar Relatório\n                                                </Button>\n                                            </div>\n                                        </DialogContent>\n                                    </Dialog>', 'Visualizar Relatório\n                                                </Button>\n                                            </div>\n                                        </DialogContent>\n                                    </Dialog>) : (\n                                      <Button variant="ghost" disabled className="w-full justify-start text-slate-400 py-5 border border-white/30 rounded-2xl cursor-not-allowed">\n                                          <FileSpreadsheet className="w-4 h-4 mr-3 text-slate-300" />\n                                          <div className="text-left">\n                                              <div className="font-medium" style={{ fontFamily: "var(--font-inter)" }}>Relatório por Promotor</div>\n                                              <div className="text-xs text-slate-400" style={{ fontFamily: "var(--font-inter)" }}>Bloqueado</div>\n                                          </div>\n                                      </Button>\n                                    )}')


with open("app/admin/(protected)/dashboard/DashboardClient.tsx", "w") as f:
    f.write(content)

print("Dashboard client patched successfully.")
